# air.toml

# Root directory for the project
root = "."
tmp_dir = "tmp"

# Watch these directories and files
[watcher]
  # File extensions to watch
  extensions = ["go", "tpl", "tmpl", "html"]
  # Ignore files or folders (regex)
  ignore = ["tmp/*", "vendor/*"]

# Build and run settings
[build]
  # Main Go file to build (relative to root)
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = ""
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go"]
  exclude_ext = ["swp"]
  log = "build.log"

# Logging
[log]
  level = "debug"

# Enable/disable app restart on file save
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
